/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package construtoraInterface;

import model.dao.ConstrucaoDAO;
import model.bean.Construcao;
import model.bean.Material;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import construtoraInterface.janelaInterna1;
import java.awt.Point;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.bean.Funcionario;
import model.dao.EstabelecerConexao;
import model.dao.FuncionarioDAO;
import model.dao.MaterialDAO;

/**
 *
 * @author Neto
 */
public class janelaInterna3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form janelaInterna3
     */
    
    ArrayList<Construcao> construcoes;   
    
    janelaInternaConstrucaoDados janelaInternaConstrucaoDados;
    Object[] objFunc;
    DefaultTableModel tableInterna3Func;
    Funcionario fEscolhido;
    
    public janelaInterna3(ArrayList<Construcao> cons) {
        initComponents();
        construcoes = cons;                
        jDesktopPaneMain.setVisible(true);
        jDesktopPane1.setVisible(false);
        this.recupera();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jPanelBranco = new javax.swing.JPanel();
        jPanelAzul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtEndereco = new javax.swing.JTextField();
        jCadastrarCons = new javax.swing.JButton();
        jExcluirCons = new javax.swing.JButton();
        jtxtInicio = new javax.swing.JFormattedTextField();
        jtxtEntrega1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtInicio1 = new javax.swing.JFormattedTextField();
        txtEntrega1 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEndereco1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(620, 470));
        getContentPane().setLayout(null);

        jDesktopPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPaneMain.setPreferredSize(new java.awt.Dimension(620, 470));

        jPanelBranco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBranco.setLayout(null);

        jPanelAzul.setBackground(new java.awt.Color(0, 102, 255));
        jPanelAzul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descrição");
        jPanelAzul.add(jLabel1);
        jLabel1.setBounds(10, 20, 180, 30);

        jtxtNome.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtNome.setForeground(new java.awt.Color(0, 102, 255));
        jtxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanelAzul.add(jtxtNome);
        jtxtNome.setBounds(10, 50, 180, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Início");
        jPanelAzul.add(jLabel2);
        jLabel2.setBounds(200, 20, 180, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entrega");
        jPanelAzul.add(jLabel3);
        jLabel3.setBounds(390, 20, 180, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Endereço");
        jPanelAzul.add(jLabel4);
        jLabel4.setBounds(10, 100, 180, 30);

        jtxtEndereco.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtEndereco.setForeground(new java.awt.Color(0, 102, 255));
        jtxtEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanelAzul.add(jtxtEndereco);
        jtxtEndereco.setBounds(10, 130, 180, 30);

        jCadastrarCons.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jCadastrarCons.setForeground(new java.awt.Color(255, 255, 255));
        jCadastrarCons.setText("Cadastrar");
        jCadastrarCons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jCadastrarCons.setContentAreaFilled(false);
        jCadastrarCons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCadastrarConsMouseClicked(evt);
            }
        });
        jCadastrarCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarConsActionPerformed(evt);
            }
        });
        jPanelAzul.add(jCadastrarCons);
        jCadastrarCons.setBounds(200, 130, 180, 30);

        jExcluirCons.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jExcluirCons.setForeground(new java.awt.Color(255, 255, 255));
        jExcluirCons.setText("Excluir");
        jExcluirCons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jExcluirCons.setContentAreaFilled(false);
        jExcluirCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirConsActionPerformed(evt);
            }
        });
        jPanelAzul.add(jExcluirCons);
        jExcluirCons.setBounds(390, 130, 180, 30);

        jtxtInicio.setBorder(null);
        jtxtInicio.setForeground(new java.awt.Color(0, 102, 255));
        try {
            jtxtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtInicio.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelAzul.add(jtxtInicio);
        jtxtInicio.setBounds(200, 50, 180, 30);

        jtxtEntrega1.setBorder(null);
        jtxtEntrega1.setForeground(new java.awt.Color(0, 102, 255));
        try {
            jtxtEntrega1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtEntrega1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanelAzul.add(jtxtEntrega1);
        jtxtEntrega1.setBounds(390, 50, 180, 30);

        jPanelBranco.add(jPanelAzul);
        jPanelAzul.setBounds(0, 0, 620, 220);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Inicio", "Entrega", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        jPanelBranco.add(jScrollPane1);
        jScrollPane1.setBounds(0, 220, 620, 230);

        jDesktopPaneMain.add(jPanelBranco);
        jPanelBranco.setBounds(0, 1, 620, 470);

        getContentPane().add(jDesktopPaneMain);
        jDesktopPaneMain.setBounds(0, 0, 620, 470);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Descrição");

        txtNome1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtNome1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Início");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Entrega");

        txtInicio1.setForeground(new java.awt.Color(0, 102, 255));
        try {
            txtInicio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtInicio1.setCaretColor(new java.awt.Color(0, 102, 255));
        txtInicio1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        txtEntrega1.setForeground(new java.awt.Color(0, 102, 255));
        try {
            txtEntrega1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEntrega1.setCaretColor(new java.awt.Color(0, 102, 255));
        txtEntrega1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Endereço");

        txtEndereco1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtEndereco1.setForeground(new java.awt.Color(0, 102, 255));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Atualizar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("ID");

        txtID1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtID1.setForeground(new java.awt.Color(0, 102, 255));
        txtID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 470);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 620, 470);

        setBounds(0, 0, 620, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void jCadastrarConsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCadastrarConsMouseClicked

    }//GEN-LAST:event_jCadastrarConsMouseClicked
        
    private void jCadastrarConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarConsActionPerformed
        int i = 0;
        //Adiciona no JTableCons
        if(this.isNullOrEmpty(jtxtNome.getText()) || this.isNullOrEmpty(jtxtInicio.getText()) || this.isNullOrEmpty(jtxtInicio.getText()) || this.isNullOrEmpty(jtxtEndereco.getText())){
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        }else{
            
            EstabelecerConexao con = new EstabelecerConexao();
            ConstrucaoDAO construcaodao = new ConstrucaoDAO(con);
            Construcao c = new Construcao();
                           
            c.setNome(jtxtNome.getText());
            Date date1 = Date.valueOf(jtxtInicio.getText());
            c.setData_Inicio(date1);
            Date date2 = Date.valueOf(jtxtInicio.getText());
            c.setData_Entrega(date2);
            c.setEndereco(jtxtEndereco.getText());
            
            //Adiciona no Banco de Dados
            construcaodao.AdicionarConstrucao(c);
            
            DefaultTableModel tableCons = (DefaultTableModel) jTable3.getModel();
            Object[] objCons = {c.getId(),jtxtNome.getText(), jtxtInicio.getText(), jtxtInicio.getText(), jtxtEndereco.getText()};
            tableCons.addRow(objCons);
            
            this.apaga();
            this.recupera();
        }                
        
    }//GEN-LAST:event_jCadastrarConsActionPerformed
    
    /*
    public void setDadosFunc(int ID, String CPF, String Nome, String Sexo, String Nasc, double Salario, boolean Disponibilidade){                
        FuncEscolhidos.add(ID);        
    }*/
    
    public boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }
    
    private void jExcluirConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirConsActionPerformed
        if(jTable3.getSelectedRow() != -1){
            
            int Id = Integer.valueOf(jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());            
            System.out.println(Id);
            
            
            EstabelecerConexao con = new EstabelecerConexao();
            ConstrucaoDAO construcaodao = new ConstrucaoDAO(con);
            construcaodao.DeletarConstrucao(Id);
                   
            DefaultTableModel tableCons = (DefaultTableModel) jTable3.getModel();//Tabela
            tableCons.removeRow(jTable3.getSelectedRow());            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }   
    }//GEN-LAST:event_jExcluirConsActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
            Point p = evt.getPoint();  
            int row = jTable3.rowAtPoint(p);  
            int col = jTable3.columnAtPoint(p);  
            //System.out.printf("row: %d    col: %d\n", row, col);
            
            int ID = Integer.parseInt(jTable3.getValueAt(row, 0).toString());
            String Nome = jTable3.getValueAt(row, 1).toString();
            String DataInicio = jTable3.getValueAt(row, 2).toString();
            String DataEntrega = jTable3.getValueAt(row, 3).toString();
            String Endereco = jTable3.getValueAt(row, 4).toString();                        
            
            if (evt.getClickCount() == 2){  
                jDesktopPane1.setVisible(true);
                jDesktopPaneMain.setVisible(false);
                
                txtID1.setText(String.valueOf(ID));
                txtNome1.setText(Nome);
                txtInicio1.setText(DataInicio);
                txtEntrega1.setText(DataEntrega);
                txtEndereco1.setText(Endereco);
                /*
                janelaInternaConstrucaoDados = new janelaInternaConstrucaoDados(ID,Nome,DataInicio,DataEntrega,Endereco);
                jDesktopPaneMain.add(janelaInternaConstrucaoDados);
                janelaInternaConstrucaoDados.setVisible(true);
                ((BasicInternalFrameUI)janelaInternaConstrucaoDados.getUI()).setNorthPane(null);
                janelaInternaConstrucaoDados.setBorder(null);//retirar bordas
                  */   
            }  
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EstabelecerConexao con = new EstabelecerConexao();
        ConstrucaoDAO construcaodao = new ConstrucaoDAO(con);
        Construcao c = new Construcao();

        c.setId(Integer.parseInt(txtID1.getText()));
        c.setNome(txtNome1.getText());
        Date date1 = Date.valueOf(txtInicio1.getText());
        c.setData_Inicio(date1);
        Date date2 = Date.valueOf(txtEntrega1.getText());
        c.setData_Entrega(date2);
        c.setEndereco(txtEndereco1.getText());

        construcaodao.AtualizarConstrucao(c);
        jDesktopPane1.setVisible(false);
        jDesktopPaneMain.setVisible(true);
        
        this.apaga();
        this.recupera();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDesktopPane1.setVisible(false);
        jDesktopPaneMain.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void apaga(){
        DefaultTableModel tableCons = (DefaultTableModel) jTable3.getModel();
        while(tableCons.getRowCount() != 0){
                tableCons.removeRow(0);                
            }
    }
    private void recupera(){
        EstabelecerConexao con = new EstabelecerConexao();
        ConstrucaoDAO construcaoDao = new ConstrucaoDAO(con);
        
        ArrayList<Construcao> lista = construcaoDao.RecuperaTudo();        
                
        //Recuperar os Funcionarios do Banco de Dados e adiciona na JTableMaterial       
        DefaultTableModel tabCons = (DefaultTableModel) jTable3.getModel();
        for(Construcao c: lista){            
            Object[] objConstrucoes = {c.getId(), c.getNome(), c.getData_Inicio(), c.getData_Entrega(), c.getEndereco()};
            tabCons.addRow(objConstrucoes);
        }    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCadastrarCons;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JButton jExcluirCons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelBranco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jtxtEndereco;
    private javax.swing.JFormattedTextField jtxtEntrega1;
    private javax.swing.JFormattedTextField jtxtInicio;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField txtEndereco1;
    private javax.swing.JFormattedTextField txtEntrega1;
    private javax.swing.JLabel txtID1;
    private javax.swing.JFormattedTextField txtInicio1;
    private javax.swing.JTextField txtNome1;
    // End of variables declaration//GEN-END:variables
}
