/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package construtoraInterface;

import java.awt.Point;
import model.bean.Funcionario;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.dao.FuncionarioDAO;
import javax.swing.JInternalFrame;

/**
 *
 * @author Neto
 */
public class janelaInterna3Func extends janelaInterna3 {
    ArrayList<Funcionario> funcionarios;
    janelaInterna3 janelaInterna3;
    
    public janelaInterna3Func() {
        initComponents();        
        
        FuncionarioDAO funcDAO = new FuncionarioDAO();
        
        //Recuperar os Funcionarios do Banco de Dados e adiciona na JTableFuncionario  
        DefaultTableModel tableFuncInterna = (DefaultTableModel) jTable3Interna.getModel();//Tabela            
        for(Funcionario f: funcDAO.findAll()){            
            Object[] objFuncInterna = {f.getId(), f.getCpf(),f.getNome(), f.getSexo(), f.getDataNascimento(), f.getSalario(), f.isDisponibilidade()};
            tableFuncInterna.addRow(objFuncInterna);                        
        }         
    }
      
     /*
        ConstrucaoDAO consDAO = new ConstrucaoDAO();
        
        for(Funcionario f: consDAO.findFuncionario()){
            DefaultTableModel tableFuncInterna = (DefaultTableModel) jTable3Interna.getModel();
            Object[] objFuncInterna = {f.getId(), f.getCpf(),f.getNome(), f.getSexo(), f.getDataNascimento(), f.getSalario(), f.isDisponibilidade()};
            tableFuncInterna.addRow(objFuncInterna);
        }  */ 
    
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBranco = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3Interna = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jSelecionar = new javax.swing.JButton();
        jVoltar = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBranco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBranco.setLayout(null);

        jTable3Interna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Nome", "Sexo", "Nascimento", "Salario", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3Interna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3InternaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3Interna);
        if (jTable3Interna.getColumnModel().getColumnCount() > 0) {
            jTable3Interna.getColumnModel().getColumn(0).setResizable(false);
            jTable3Interna.getColumnModel().getColumn(1).setResizable(false);
            jTable3Interna.getColumnModel().getColumn(2).setResizable(false);
            jTable3Interna.getColumnModel().getColumn(3).setResizable(false);
            jTable3Interna.getColumnModel().getColumn(4).setResizable(false);
            jTable3Interna.getColumnModel().getColumn(5).setResizable(false);
            jTable3Interna.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanelBranco.add(jScrollPane1);
        jScrollPane1.setBounds(0, 170, 620, 270);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jSelecionar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jSelecionar.setForeground(new java.awt.Color(255, 255, 255));
        jSelecionar.setText("Selecionar");
        jSelecionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jSelecionar.setContentAreaFilled(false);
        jSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelecionarActionPerformed(evt);
            }
        });
        jPanel1.add(jSelecionar);
        jSelecionar.setBounds(100, 90, 180, 30);

        jVoltar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jVoltar.setText("Voltar");
        jVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jVoltar.setContentAreaFilled(false);
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jVoltar);
        jVoltar.setBounds(310, 90, 180, 30);

        jPanelBranco.add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 170);

        getContentPane().add(jPanelBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        setBounds(0, 0, 620, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelecionarActionPerformed
        
    }//GEN-LAST:event_jSelecionarActionPerformed

    private void jTable3InternaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3InternaMouseClicked
       
            Point p = evt.getPoint();  
            int row = jTable3Interna.rowAtPoint(p);  
            int col = jTable3Interna.columnAtPoint(p);  
            //System.out.printf("row: %d    col: %d\n", row, col);
            int ID = Integer.parseInt(jTable3Interna.getValueAt(row, 0).toString());
            String CPF = jTable3Interna.getValueAt(row, 1).toString();
            String Nome = jTable3Interna.getValueAt(row, 2).toString();
            String Sexo = jTable3Interna.getValueAt(row, 3).toString();
            String Nasc = jTable3Interna.getValueAt(row, 4).toString();
            double Salario = Double.parseDouble(jTable3Interna.getValueAt(row, 5).toString());
            boolean Disponibilidade = Boolean.valueOf(jTable3Interna.getValueAt(row, 6).toString());                                                 
        if (evt.getClickCount() == 2){             
            super.setDadosFunc(ID, CPF, Nome, Sexo, Nasc, Salario, Disponibilidade);
            this.setVisible(false);
        }                         
    }//GEN-LAST:event_jTable3InternaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBranco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSelecionar;
    private javax.swing.JTable jTable3Interna;
    private javax.swing.JButton jVoltar;
    // End of variables declaration//GEN-END:variables
}
