/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package construtoraInterface;

import model.dao.EstabelecerConexao;
import model.dao.FuncionarioDAO;
import model.bean.Construcao;
import model.bean.Funcionario;
import model.bean.Material;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Point;
import java.sql.Date;
import javax.swing.JDesktopPane;
//import construtoraInterface.janelaInternaFuncDados;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author Neto
 */
public class janelaInterna1 extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form janelaInterna1
     */
    janelaInterna3 JanelaInterna3;
    janelaInterna1 JanelaInterna1;
    janelaInterna2 JanelaInterna2;
    janelaInternaFuncDados janelaInternaFuncDados;
    JDesktopPane jDesktop;
        
    
    ArrayList<Material> materiais = new ArrayList<Material>();
    ArrayList<Construcao> construcoes = new ArrayList<Construcao>();
    
    public janelaInterna1(JDesktopPane jfunc) {
        initComponents();        
        jDesktop = jfunc;        
        jDesktopInterno1Func.setVisible(true);
        jDesktopPane1.setVisible(false);
        this.recupera();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopInterno1Func = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jCadastrarFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        jExcluirFunc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCPF = new javax.swing.JFormattedTextField();
        jDate = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtIDCons = new javax.swing.JTextField();
        jPanelFundo = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelBlue = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jNome1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSalario1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSexo1 = new javax.swing.JTextField();
        jVoltar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdisp1 = new javax.swing.JTextField();
        labelID1 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIDC1 = new javax.swing.JTextField();
        jNascimento1 = new javax.swing.JFormattedTextField();
        jCPF1 = new javax.swing.JFormattedTextField();

        setBorder(null);
        getContentPane().setLayout(null);

        jDesktopInterno1Func.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Nome", "Sexo", "Nascimento", "Salário", "Disponivel", "ID Construção"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jDesktopInterno1Func.add(jScrollPane1);
        jScrollPane1.setBounds(0, 220, 620, 230);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        jCadastrarFunc.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jCadastrarFunc.setForeground(new java.awt.Color(255, 255, 255));
        jCadastrarFunc.setText("Cadastrar");
        jCadastrarFunc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jCadastrarFunc.setContentAreaFilled(false);
        jCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarFuncActionPerformed(evt);
            }
        });
        jPanel2.add(jCadastrarFunc);
        jCadastrarFunc.setBounds(420, 130, 150, 35);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 180, 30);

        jtxtNome.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtNome.setForeground(new java.awt.Color(0, 102, 255));
        jtxtNome.setBorder(null);
        jPanel2.add(jtxtNome);
        jtxtNome.setBounds(10, 50, 180, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nascimento");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 20, 180, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salário");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(390, 20, 180, 30);

        jtxtSalario.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtSalario.setForeground(new java.awt.Color(0, 102, 255));
        jtxtSalario.setBorder(null);
        jPanel2.add(jtxtSalario);
        jtxtSalario.setBounds(390, 50, 180, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sexo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 100, 60, 30);

        jComboSexo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboSexo.setForeground(new java.awt.Color(0, 102, 255));
        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        jComboSexo.setBorder(null);
        jPanel2.add(jComboSexo);
        jComboSexo.setBounds(200, 130, 160, 30);

        jExcluirFunc.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jExcluirFunc.setForeground(new java.awt.Color(255, 255, 255));
        jExcluirFunc.setText("Excluir");
        jExcluirFunc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jExcluirFunc.setContentAreaFilled(false);
        jExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirFuncActionPerformed(evt);
            }
        });
        jPanel2.add(jExcluirFunc);
        jExcluirFunc.setBounds(420, 170, 150, 35);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 180, 30);

        jCPF.setBorder(null);
        jCPF.setForeground(new java.awt.Color(0, 102, 255));
        try {
            jCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanel2.add(jCPF);
        jCPF.setBounds(10, 130, 180, 30);

        jDate.setBorder(null);
        jDate.setForeground(new java.awt.Color(0, 102, 255));
        try {
            jDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDate.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanel2.add(jDate);
        jDate.setBounds(200, 50, 180, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Construção");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 180, 180, 30);

        jtxtIDCons.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtIDCons.setForeground(new java.awt.Color(0, 102, 255));
        jtxtIDCons.setBorder(null);
        jtxtIDCons.setCaretColor(new java.awt.Color(0, 102, 255));
        jPanel2.add(jtxtIDCons);
        jtxtIDCons.setBounds(200, 180, 60, 30);

        jDesktopInterno1Func.add(jPanel2);
        jPanel2.setBounds(0, 0, 620, 220);

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setPreferredSize(new java.awt.Dimension(620, 470));
        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDesktopInterno1Func.add(jPanelFundo);
        jPanelFundo.setBounds(0, 0, 620, 470);

        getContentPane().add(jDesktopInterno1Func);
        jDesktopInterno1Func.setBounds(0, 0, 620, 470);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBlue.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 255));
        jLabel15.setText("Nome");

        jNome1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jNome1.setForeground(new java.awt.Color(0, 102, 255));
        jNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNome1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setText("Nascimento");

        jSalario1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jSalario1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setText("Salário");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setText("CPF");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setText("Sexo");

        jSexo1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jSexo1.setForeground(new java.awt.Color(0, 102, 255));

        jVoltar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jVoltar.setForeground(new java.awt.Color(0, 102, 255));
        jVoltar.setText("Voltar");
        jVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jVoltar.setContentAreaFilled(false);
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 255));
        jLabel20.setText("ID");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Disponível");

        jdisp1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jdisp1.setForeground(new java.awt.Color(0, 102, 255));

        labelID1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        labelID1.setForeground(new java.awt.Color(0, 102, 255));
        labelID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        jButtonCadastrar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonCadastrar.setForeground(new java.awt.Color(0, 102, 255));
        jButtonCadastrar.setText("Atualizar");
        jButtonCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jButtonCadastrar.setContentAreaFilled(false);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("ID Construção");

        txtIDC1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtIDC1.setForeground(new java.awt.Color(0, 102, 255));

        jNascimento1.setForeground(new java.awt.Color(0, 102, 255));
        try {
            jNascimento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jNascimento1.setCaretColor(new java.awt.Color(0, 102, 255));
        jNascimento1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jCPF1.setForeground(new java.awt.Color(0, 102, 255));
        try {
            jCPF1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF1.setCaretColor(new java.awt.Color(0, 102, 255));
        jCPF1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlueLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBlueLayout.createSequentialGroup()
                        .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlueLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(jPanelBlueLayout.createSequentialGroup()
                                .addComponent(labelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtIDC1)))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jNome1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jNascimento1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jCPF1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBlueLayout.createSequentialGroup()
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addComponent(jSexo1)
                    .addComponent(jLabel17)
                    .addComponent(jSalario1)
                    .addComponent(jLabel19)
                    .addComponent(jdisp1))
                .addGap(44, 44, 44))
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlueLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdisp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNascimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBlueLayout.createSequentialGroup()
                        .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jDesktopPane1.add(jPanelBlue);
        jPanelBlue.setBounds(0, 0, 620, 470);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 620, 470);

        setBounds(0, 0, 620, 470);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarFuncActionPerformed
        //TOTALMENTE FUNCIONAL        
        //Adiciona na JTableFuncionario
        
        if(this.isNullOrEmpty(jtxtNome.getText()) || this.isNullOrEmpty(jCPF.getText()) || this.isNullOrEmpty((String)jComboSexo.getSelectedItem())|| this.isNullOrEmpty(jtxtSalario.getText()) || this.isNullOrEmpty(jtxtIDCons.getText())){
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        }else{
            EstabelecerConexao con2 = new EstabelecerConexao();
            FuncionarioDAO funDao2 = new FuncionarioDAO(con2);
            Funcionario f = new Funcionario();
            
            f.setNome(jtxtNome.getText());
            f.setCpf(jCPF.getText());
            f.setSexo((String)jComboSexo.getSelectedItem());
            
            Date date = Date.valueOf(jDate.getText());
            f.setDataNascimento(date);
           // f.setDataNascimento(jDate.getText());
            f.setSalario(Double.parseDouble(jtxtSalario.getText()));
            f.setDisponibilidade(true);
            f.setId_Construcao(Integer.parseInt(jtxtIDCons.getText()));
            //Adiciona no Banco de Dados
            funDao2.AdicionaFuncionario(f);                        
            
            //Adicionar na JTable
            DefaultTableModel tableFunc = (DefaultTableModel) jTable1.getModel();//Tabela
            Object[] objFuncionarios = {f.getId(), jCPF.getText(), jtxtNome.getText(), (String)jComboSexo.getSelectedItem(), jDate.getText(), Double.parseDouble(jtxtSalario.getText()), true, f.getId_Construcao()};
            tableFunc.addRow(objFuncionarios);
            this.apaga();
            this.recupera();
        }
        
        
        
    }//GEN-LAST:event_jCadastrarFuncActionPerformed

    public boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }
    private void jExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirFuncActionPerformed
        
        if(jTable1.getSelectedRow() != -1){
                        
            int Id = Integer.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());            
            System.out.println(Id);
            
            EstabelecerConexao con = new EstabelecerConexao();
            FuncionarioDAO fundao = new FuncionarioDAO(con);
            fundao.DeletarFuncionario(Id);  
            
            DefaultTableModel tableFunc = (DefaultTableModel) jTable1.getModel();//Tabela
            tableFunc.removeRow(jTable1.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }   
    }//GEN-LAST:event_jExcluirFuncActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            Point p = evt.getPoint();  
            int row = jTable1.rowAtPoint(p);  
            int col = jTable1.columnAtPoint(p);  
            //System.out.printf("row: %d    col: %d\n", row, col);
            int ID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            String CPF = jTable1.getValueAt(row, 1).toString();
            String Nome = jTable1.getValueAt(row, 2).toString();
            String Sexo = jTable1.getValueAt(row, 3).toString();
            String Nasc = jTable1.getValueAt(row, 4).toString();
            double Salario = Double.parseDouble(jTable1.getValueAt(row, 5).toString());                        
            boolean Disponibilidade = Boolean.valueOf(jTable1.getValueAt(row, 6).toString()); 
            int ID_Cons = Integer.parseInt(jTable1.getValueAt(row,7).toString());
            
        if (evt.getClickCount() == 2){  
            jDesktopInterno1Func.setVisible(false);    
            jDesktopPane1.setVisible(true);
                
            jNome1.setText(Nome);
            jSalario1.setText(String.valueOf(Salario));
            jCPF1.setText(CPF);
            jNascimento1.setText(String.valueOf(Nasc));
            jSexo1.setText(Sexo);
            labelID1.setText(String.valueOf(ID));
            jdisp1.setText(String.valueOf(Disponibilidade));
            txtIDC1.setText(String.valueOf(ID_Cons));
            
            
            
                /*
                janelaInternaFuncDados = new janelaInternaFuncDados(ID,CPF,Nome,Sexo,Nasc,Salario,Disponibilidade,ID_Cons);
                jDesktopInterno1Func.add(janelaInternaFuncDados);
                janelaInternaFuncDados.setVisible(true);
                ((BasicInternalFrameUI)janelaInternaFuncDados.getUI()).setNorthPane(null);
                janelaInternaFuncDados.setBorder(null);//retirar bordas  */                   
        }  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNome1ActionPerformed

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        jDesktopPane1.setVisible(false);
        jDesktopInterno1Func.setVisible(true);
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed

        EstabelecerConexao con2 = new EstabelecerConexao();
        FuncionarioDAO funDao2 = new FuncionarioDAO(con2);
        Funcionario fun = new Funcionario();

        fun.setCpf(jCPF1.getText());
        Date date = Date.valueOf(jNascimento1.getText());
        fun.setDataNascimento(date);
        fun.setDisponibilidade(Boolean.parseBoolean(jdisp1.getText()));
        fun.setNome(jNome1.getText());
        fun.setSalario(Double.parseDouble(jSalario1.getText()));
        fun.setSexo(jSexo1.getText());
        fun.setId_Construcao(Integer.parseInt(txtIDC1.getText()));
        fun.setId(Integer.parseInt(labelID1.getText()));

        funDao2.AtualizarFuncionario(fun);
        jDesktopPane1.setVisible(false);
        jDesktopInterno1Func.setVisible(true);
        
        this.apaga();
        this.recupera();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    
    private void apaga(){ 
            DefaultTableModel tableFunc = (DefaultTableModel) jTable1.getModel();//Tabela
            while(tableFunc.getRowCount() != 0){
                tableFunc.removeRow(0);                
            }                      
    }
    
    private void recupera(){
        EstabelecerConexao con = new EstabelecerConexao();
        FuncionarioDAO FunDAO = new FuncionarioDAO(con);               
          
        ArrayList<Funcionario> arrayfun = FunDAO.RecuperarTudo();
        System.out.println(arrayfun);
            
        //Recuperar os Funcionarios do Banco de Dados e adiciona na JTableFuncionario       
        DefaultTableModel tableFunc = (DefaultTableModel) jTable1.getModel();//Tabela            
        for(Funcionario f: arrayfun){                        
            Object[] objFuncionarios = {f.getId(), f.getCpf(),f.getNome(), f.getSexo(), f.getDataNascimento(), f.getSalario(), f.isDisponibilidade(),f.getId_Construcao()};
            tableFunc.addRow(objFuncionarios);                        
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JFormattedTextField jCPF;
    private javax.swing.JFormattedTextField jCPF1;
    private javax.swing.JButton jCadastrarFunc;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JFormattedTextField jDate;
    private javax.swing.JDesktopPane jDesktopInterno1Func;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jExcluirFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField jNascimento1;
    private javax.swing.JTextField jNome1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JTextField jSalario1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSexo1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jVoltar;
    private javax.swing.JTextField jdisp1;
    private javax.swing.JTextField jtxtIDCons;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtSalario;
    private javax.swing.JLabel labelID1;
    private javax.swing.JTextField txtIDC1;
    // End of variables declaration//GEN-END:variables
}
