/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package construtoraInterface;

import java.awt.Point;
import model.dao.MaterialDAO;
import model.bean.Material;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.dao.EstabelecerConexao;

/**
 *
 * @author Neto
 */
public class janelaInterna2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form janelaInterna2
     */
    
    ArrayList<Material> materiais;
    janelaInternaMatDados janelaInternaMatDados;
    
    public janelaInterna2(ArrayList<Material> mat) {
        initComponents();
        materiais = mat;        
        jDesktopPaneMain.setVisible(true);
        jDesktopPane1.setVisible(false);
        this.recupera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jPaneldeFundo = new javax.swing.JPanel();
        jPanelAzul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtQtd = new javax.swing.JTextField();
        jtxtPreco = new javax.swing.JTextField();
        jCadastrarMat = new javax.swing.JButton();
        jExcluirMat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFornecedor1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstoque1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        setPreferredSize(new java.awt.Dimension(620, 470));
        getContentPane().setLayout(null);

        jDesktopPaneMain.setBackground(new java.awt.Color(255, 255, 255));

        jPaneldeFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPaneldeFundo.setLayout(null);

        jPanelAzul.setBackground(new java.awt.Color(0, 102, 255));
        jPanelAzul.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAzul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        jPanelAzul.add(jLabel1);
        jLabel1.setBounds(10, 20, 180, 30);

        jtxtNome.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtNome.setForeground(new java.awt.Color(0, 102, 255));
        jtxtNome.setBorder(null);
        jPanelAzul.add(jtxtNome);
        jtxtNome.setBounds(10, 50, 180, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preço");
        jPanelAzul.add(jLabel2);
        jLabel2.setBounds(200, 20, 180, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fornecedor");
        jPanelAzul.add(jLabel3);
        jLabel3.setBounds(390, 20, 180, 30);

        jtxtFornecedor.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtFornecedor.setForeground(new java.awt.Color(0, 102, 255));
        jtxtFornecedor.setBorder(null);
        jPanelAzul.add(jtxtFornecedor);
        jtxtFornecedor.setBounds(390, 50, 180, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade");
        jPanelAzul.add(jLabel4);
        jLabel4.setBounds(10, 110, 130, 30);

        jtxtQtd.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtQtd.setForeground(new java.awt.Color(0, 102, 255));
        jtxtQtd.setBorder(null);
        jPanelAzul.add(jtxtQtd);
        jtxtQtd.setBounds(140, 110, 50, 30);

        jtxtPreco.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jtxtPreco.setForeground(new java.awt.Color(0, 102, 255));
        jtxtPreco.setBorder(null);
        jPanelAzul.add(jtxtPreco);
        jtxtPreco.setBounds(200, 50, 180, 30);

        jCadastrarMat.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jCadastrarMat.setForeground(new java.awt.Color(255, 255, 255));
        jCadastrarMat.setText("Cadastrar");
        jCadastrarMat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jCadastrarMat.setContentAreaFilled(false);
        jCadastrarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarMatActionPerformed(evt);
            }
        });
        jPanelAzul.add(jCadastrarMat);
        jCadastrarMat.setBounds(420, 130, 150, 35);

        jExcluirMat.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jExcluirMat.setForeground(new java.awt.Color(255, 255, 255));
        jExcluirMat.setText("Excluir");
        jExcluirMat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jExcluirMat.setContentAreaFilled(false);
        jExcluirMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirMatActionPerformed(evt);
            }
        });
        jPanelAzul.add(jExcluirMat);
        jExcluirMat.setBounds(420, 170, 150, 35);

        jPaneldeFundo.add(jPanelAzul);
        jPanelAzul.setBounds(0, 0, 620, 220);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Fornecedor", "Estoque", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jPaneldeFundo.add(jScrollPane1);
        jScrollPane1.setBounds(0, 220, 620, 230);

        jDesktopPaneMain.add(jPaneldeFundo);
        jPaneldeFundo.setBounds(0, 0, 620, 470);

        getContentPane().add(jDesktopPaneMain);
        jDesktopPaneMain.setBounds(0, 0, 620, 470);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Nome");

        txtNome1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtNome1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Preço");

        txtPreco1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtPreco1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Fornecedor");

        txtFornecedor1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtFornecedor1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Estoque");

        txtEstoque1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtEstoque1.setForeground(new java.awt.Color(0, 102, 255));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Atualizar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("ID");

        txtID1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtID1.setForeground(new java.awt.Color(0, 102, 255));
        txtID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFornecedor1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtPreco1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtEstoque1))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEstoque1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                        .addGap(233, 233, 233)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 470);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 620, 470);

        setBounds(0, 0, 620, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void jExcluirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirMatActionPerformed
        if(jTable2.getSelectedRow() != -1){
            
            int Id = Integer.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());            
            System.out.println(Id);
            
            
            EstabelecerConexao con = new EstabelecerConexao();
            MaterialDAO materialdao = new MaterialDAO(con);
            materialdao.DeletarMaterial(Id);
            
            DefaultTableModel tableMat = (DefaultTableModel) jTable2.getModel();//Tabela
            tableMat.removeRow(jTable2.getSelectedRow());                        
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!");
        }   
    }//GEN-LAST:event_jExcluirMatActionPerformed

    private void jCadastrarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarMatActionPerformed
        int i = 0;
        //Adiciona no JTableMat   
        if(this.isNullOrEmpty(jtxtNome.getText()) || this.isNullOrEmpty(jtxtFornecedor.getText()) || this.isNullOrEmpty(jtxtQtd.getText()) || this.isNullOrEmpty(jtxtPreco.getText())){
             JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        }else{
            EstabelecerConexao con = new EstabelecerConexao();
            MaterialDAO MatDao = new MaterialDAO(con);
            Material m = new Material();
            
            m.setNome(jtxtNome.getText());
            m.setFornecedor(jtxtFornecedor.getText());
            m.setEstoque(Integer.parseInt(jtxtQtd.getText()));
            m.setPreco(Double.parseDouble(jtxtPreco.getText()));
            //Adiciona no Banco de Dados
            MatDao.AdicionaMaterial(m);
            
            //Adiciona no JTable
            DefaultTableModel tableMat = (DefaultTableModel) jTable2.getModel();
            Object[] objMateriais = {m.getId(), jtxtNome.getText(), jtxtFornecedor.getText(), Integer.parseInt(jtxtQtd.getText()), Double.parseDouble(jtxtPreco.getText())};
            tableMat.addRow(objMateriais);
            this.apaga();
            this.recupera();
        }                 
    }//GEN-LAST:event_jCadastrarMatActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        Point p = evt.getPoint();  
            int row = jTable2.rowAtPoint(p);  
            int col = jTable2.columnAtPoint(p);  
            //System.out.printf("row: %d    col: %d\n", row, col);
            int ID = Integer.parseInt(jTable2.getValueAt(row, 0).toString());            
            String Nome = jTable2.getValueAt(row, 1).toString();
            String Fornecedor = jTable2.getValueAt(row, 2).toString();
            int Estoque = Integer.parseInt(jTable2.getValueAt(row, 3).toString());
            double Preco = Double.parseDouble(jTable2.getValueAt(row, 4).toString());                                    
                        
        if (evt.getClickCount() == 2){  
                jDesktopPane1.setVisible(true);
                jDesktopPaneMain.setVisible(false);
            
                txtID1.setText(String.valueOf(ID));
                txtNome1.setText(Nome);
                txtFornecedor1.setText(Fornecedor);
                txtEstoque1.setText(String.valueOf(Estoque));
                txtPreco1.setText(String.valueOf(Preco));   
                /*
                janelaInternaMatDados = new janelaInternaMatDados(ID,Nome,Fornecedor,Estoque,Preco);
                jDesktopPaneMain.add(janelaInternaMatDados);
                janelaInternaMatDados.setVisible(true);
                ((BasicInternalFrameUI)janelaInternaMatDados.getUI()).setNorthPane(null);
                janelaInternaMatDados.setBorder(null);//retirar bordas
                 */    
        }  
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EstabelecerConexao con = new EstabelecerConexao();
        MaterialDAO materialdao = new MaterialDAO(con);
        Material m = new Material();

        m.setNome(txtNome1.getText());
        m.setFornecedor(txtFornecedor1.getText());
        m.setEstoque(Integer.parseInt(txtEstoque1.getText()));
        m.setPreco(Double.parseDouble(txtPreco1.getText()));
        m.setId(Integer.parseInt(txtID1.getText()));

        materialdao.AtualizarMaterial(m);
        jDesktopPane1.setVisible(false);
        jDesktopPaneMain.setVisible(true);
        
        this.apaga();
        this.recupera();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDesktopPane1.setVisible(false);
        jDesktopPaneMain.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }
    
    private void apaga(){
        DefaultTableModel tableMat = (DefaultTableModel) jTable2.getModel();
        while(tableMat.getRowCount() != 0){
                tableMat.removeRow(0);                
            }
    }
    
    private void recupera(){
        EstabelecerConexao con = new EstabelecerConexao();
        MaterialDAO MatDao = new MaterialDAO(con);
        
        ArrayList<Material> arraymat = MatDao.RecuperaTudo();
        System.out.println(arraymat);
        
        //Recuperar os Funcionarios do Banco de Dados e adiciona na JTableMaterial       
        DefaultTableModel tabFunc = (DefaultTableModel) jTable2.getModel();
        for(Material m: arraymat){            
            Object[] objMateriais = {m.getId(), m.getNome(), m.getFornecedor(), m.getEstoque(), m.getPreco()};
            tabFunc.addRow(objMateriais);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCadastrarMat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JButton jExcluirMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPaneldeFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jtxtFornecedor;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtPreco;
    private javax.swing.JTextField jtxtQtd;
    private javax.swing.JTextField txtEstoque1;
    private javax.swing.JTextField txtFornecedor1;
    private javax.swing.JLabel txtID1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtPreco1;
    // End of variables declaration//GEN-END:variables
}
